import { createSlice } from "@reduxjs/toolkit";

//Define the initial state of the slice
const initialState = {
    balance: 0
};

//Cerate the slice using the createSlice function
const balanceSlice = createSlice({
    //Define the initial name of the slice
    name: "balance",
    //Define the initial state of the slice
    initialState,
    //Define the reducers for the slice
    reducers: {
        deposit: (state, action) => {
            state.balance += action.payload;
        },
        withdrawal: (state, action) => {
            state.balance -= action.payload;
        },
        interest: (state) => {
            state.balance *= 1.05;
        },
        charge: (state) => {
            state.balance *= 0.85
        }
    }
});

//Export the action creators generated by createSlice
export const { deposit, withdrawal, interest, charge} = balanceSlice.actions;

//Export the reducer generated by createSlice
export default balanceSlice.reducer;